version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686" # Jaeger UI port
      - "14250"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 # Port for Zipkin-compatible endpoint
      - COLLECTOR_TEXT_MAP_PROPAGATOR=http
      - COLLECTOR_INTEGRATIONS=jaeger

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
#      - "4317:4317" # OTLP gRPC port
      - "4318:4318" # HTTP port
      - "55680:55680" # Metrics port
    volumes:
      - ./collector-gateway.yaml:/etc/collector-gateway.yaml
    command: ["--config", "/etc/collector-gateway.yaml"]